### ISSUE TITLE
Should be Executor.execute instead of Executor.run

### ISSUE THREAD

**Issue by hoc081098** [xizzhu/Logger#4]
Hi @xizzhu 
Probably a mistake

https://github.com/xizzhu/Logger/blob/de6b21f0b8763219aab613359f565c048d188833/lib/src/main/kotlin/me/xizzhu/android/logger/FileLogger.kt#L34

and https://github.com/xizzhu/Logger/blob/de6b21f0b8763219aab613359f565c048d188833/lib/src/main/kotlin/me/xizzhu/android/logger/FileLogger.kt#L65

Should be
```kotlin
executor.execute {

}
```

**Comment by xizzhu** [comment]
Thanks! Fixed and released in v0.4.1.
